# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
//获取所有试题分类
GET http://localhost:8080/api/question/ModuleExercises?token=kfzjw0000

###

POST http://localhost:8080/api/question/ModuleExercisesDetails?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvY0NfdTBPMU9HVzN5dUdSOGhrc2FtQm5feER3IiwiaWQiOjQsImV4cCI6MTU3OTE5Nzk4NSwiT3BlbklkIjoib2NDX3UwTzFPR1czeXVHUjhoa3NhbUJuX3hEdyIsImlhdCI6MTU3OTE2MTk4NSwianRpIjoiNCIsIk5pY2tuYW1lIjoi5Yeg5L2V5Y-45LukIn0.xg4scNB-8Tk6ofjg2J3AlfcKURGe00YiPNFjCFpz7mE&module=4&page=2&size=1

###


POST http://localhost:8080/api/question/GetQuestion?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvY0NfdTBPMU9HVzN5dUdSOGhrc2FtQm5feER3IiwiaWQiOjQsImV4cCI6MTU3OTAwODUzMCwiT3BlbklkIjoib2NDX3U]wTzFPR1czeXVHUjhoa3NhbUJuX3hEdyIsImlhdCI6MTU3ODk3MjUzMCwianRpIjoiNCIsIk5pY2tuYW1lIjoi5Yeg5L2V5Y-45LukIn0.HBXx2Up_K-ri4_D9Hl3gfc5Vo0GdnBAoCibVNzaRIhw&id=20

###

POST http://localhost:8080/api/question/RandomGetQuestion?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvY0NfdTBPMU9HVzN5dUdSOGhrc2FtQm5feER3IiwiaWQiOjQsImV4cCI6MTU3OTAwODUzMCwiT3BlbklkIjoib2NDX3UwTzFPR1czeXVHUjhoa3NhbUJuX3hEdyIsImlhdCI6MTU3ODk3MjUzMCwianRpIjoiNCIsIk5pY2tuYW1lIjoi5Yeg5L2V5Y-45LukIn0.HBXx2Up_K-ri4_D9Hl3gfc5Vo0GdnBAoCibVNzaRIhw

###



POST http://localhost:8080/api/question/Search?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvY0NfdTBPMU9HVzN5dUdSOGhrc2FtQm5feER3IiwiaWQiOjQsImV4cCI6MTU3OTA0NTM1OCwiT3BlbklkIjoib2NDX3UwTzFPR1czeXVHUjhoa3NhbUJuX3hEdyIsImlhdCI6MTU3OTAwOTM1OCwianRpIjoiNCIsIk5pY2tuYW1lIjoi5Yeg5L2V5Y-45LukIn0._0mTS0ZXW52dyW5N615wI8Q5wCYkFTU1soi00w3KKlE&word=金星

###
POST http://localhost:8080/api/question/PutRecords?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvY0NfdTBMVlR6WW5rQjBZd3BkLXB3SGhxeHhNIiwiaWQiOjAsImV4cCI6MTU3OTA5ODU2MywiT3BlbklkIjoib2NDX3UwTFZUellua0IwWXdwZC1wd0hocXh4TSIsImlhdCI6MTU3OTA2MjU2MywianRpIjoiMCIsIk5pY2tuYW1lIjoi54On54Ok5ZCX77yfIn0.1EiFADwc2kpZ2Tn1qjro8zFLDsSE36dAHPJDtG6AgME&id=174&source=模块练习&answer=B&openid=ocC_u0LVTzYnkB0Ywpd-pwHhqxxM

###

GET http://localhost:8080/images/1.jpg

###

GET http://localhost:8080/images/moon/1_m15.jpg

###

POST http://localhost:8080/api/user/Verifytoken?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvY0NfdTBPMU9HVzN5dUdSOGhrc2FtQm5feER3IiwiaWQiOjQsImV4cCI6MTU4MDc1MDg2OSwiT3BlbklkIjoib2NDX3UwTzFPR1czeXVHUjhoa3NhbUJuX3hEdyIsImlhdCI6MTU4MDcxNDg2OSwianRpIjoiNCIsIk5pY2tuYW1lIjoi5Yeg5L2V5Y-45LukIn0.PWgOmtUIJLcf_M945PNeybXb_Fw5Thc3p7Xha7D10ZY

###

POST http://localhost:8080/api/user/Verifytoken

###

GET http://localhost:8080/api/question/FindAlllQ?token=kfzjw0000

###


GET http://localhost:8080/api/question/RecommendedExercises?token=kfzjw0000&openid=1&id=6

###